"""empty message

Revision ID: 35eab4a4402
Revises: None
Create Date: 2015-11-04 21:34:18.759466

"""

# revision identifiers, used by Alembic.
revision = '35eab4a4402'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels_statuts_fantoir',
    sa.Column('id_statut', sa.Integer(), nullable=False),
    sa.Column('tri', sa.Integer(), nullable=True),
    sa.Column('label_statut', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id_statut')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labels_statuts_fantoir')
    ### end Alembic commands ###
