"""empty message

Revision ID: 3cff0e8e69c
Revises: 35eab4a4402
Create Date: 2015-11-04 21:35:41.542216

"""

# revision identifiers, used by Alembic.
revision = '3cff0e8e69c'
down_revision = '35eab4a4402'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statut_fantoir',
    sa.Column('fantoir', sa.String(length=10), nullable=False),
    sa.Column('id_statut', sa.Integer(), nullable=True),
    sa.Column('timestamp_statut', postgresql.DOUBLE_PRECISION(), nullable=True),
    sa.Column('insee_com', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('fantoir')
    )
    op.create_index(op.f('ix_statut_fantoir_fantoir'), 'statut_fantoir', ['fantoir'], unique=False)
    op.create_index(op.f('ix_statut_fantoir_insee_com'), 'statut_fantoir', ['insee_com'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statut_fantoir_insee_com'), table_name='statut_fantoir')
    op.drop_index(op.f('ix_statut_fantoir_fantoir'), table_name='statut_fantoir')
    op.drop_table('statut_fantoir')
    ### end Alembic commands ###
